library(dplyr)
library(tidyr)
refine_data <- read.csv("~/Desktop/Springboard/Exercise 1/refine_original.csv")
refine_tbl <- as_tibble(refine_data)
refine_tbl$company <- tolower(refine_tbl$company)
refine_tbl$company <- gsub("^.*ps$", "philips", refine_tbl$company)
refine_tbl$company <- gsub("^ak.*", "akzo", refine_tbl$company)
refine_tbl <- refine_tbl %>% separate(Product.code...number, c("product_code", "product_number"), sep = "-" )
refine_tbl <- refine_tbl %>% mutate("product_category" = ifelse(product_code == "p", "Smartphone",ifelse(product_code == "v", "TV",ifelse(product_code == "x", "laptop",ifelse(product_code == "q", "Tablet","")))) )
refine_tbl$full_address <- paste(refine_tbl$address, refine_tbl$city, refine_tbl$country, sep = ", ")
refine_tbl <- refine_tbl %>% mutate(company_philips = ifelse(company == "philips", 1, 0)) %>% mutate(company_akzo = ifelse(company == "akzo", 1, 0)) %>% mutate(company_van_houten = ifelse(company == "van houten", 1, 0)) %>% mutate(company_unilever = ifelse(company == "unilever", 1, 0))
refine_tbl <- refine_tbl %>% mutate(product_smartphone = ifelse(product_category == "Smartphone", 1, 0)) %>% mutate(product_tv = ifelse(product_category == "TV", 1, 0)) %>% mutate(product_laptop = ifelse(product_category == "Laptop", 1, 0)) %>% mutate(product_tablet = ifelse(product_category == "Tablet", 1, 0))
write.csv(refine_tbl, "~/Desktop/Springboard/Exercise 1/refine_clean.csv")